---
# Base playbook for installation

- name: cfme
  hosts: local
  connection: local

  tasks:
  - include: tasks/install.yml
    vars:
        # https://${github_token}@github.com/ManageIQ/cfme.git
        github_token: github_token
        github_depth: 1
        cfme_src: github.com/ManageIQ/cfme.git
        cfme_dir: /var/www/cfme
  - include: tasks/db_config.yml
    vars:
        db_user: postgres
        db_passwd: smartvm
        db_dir: /var/lib/pgsql/data
  - include: tasks/ruby_setup.yml
    vars:
        rbenv_dir: .rbenv
        ruby_ver: 1.9.3-p327
        profile: .bash_profile
        # FIXME: use playbook-scope var $cfme_dir/vmdb
        vmdb_dir: /var/www/cfme/vmdb
        bundler_ver: 1.1.3
  - include: tasks/init_cfme.yml
    vars:
        # FIXME: dup
        vmdb_dir: /var/www/cfme/vmdb
  handlers:
  - include: handlers.yml
