---
# Base playbook for installation

- name: cfme
  hosts: local
  connection: local

  vars:
    cfme_dir: /var/www/cfme
    vmdb_dir: $cfme_dir/vmdb
  tasks:
  - include: tasks/install.yml
    vars:
        github_token: 
        cfme_src: https://$github_token@github.com/ManageIQ/cfme.git
        github_depth: 1
  - include: tasks/db_config.yml
    vars:
        db_user: postgres
        db_passwd: smartvm
        db_dir: /var/lib/pgsql/data
  - include: tasks/ruby_setup.yml
    vars:
        rbenv_dir: .rbenv
        ruby_ver: 1.9.3-p327
        profile: .bash_profile
        bundler_ver: 1.1.3
        bundle_opts: --without metric_fu:sqlserver:qpid
        gemset: cfme
  - include: tasks/init_cfme.yml
  handlers:
  - include: handlers.yml
