- name: install python-psycopg2 for ansible postgresql_db module
  yum: name=python-psycopg2 state=present

# failure when db_dir already exists on first run?
- name: init db
  command: service postgresql initdb creates=$db_dir

- name: copy postgresql.conf
  copy: src=files/postgresql.conf dest=$db_dir/postgresql.conf
          owner=$db_user group=$db_user mode=0600
  notify:
    - restart postgres

- name: copy pg_hba.conf
  copy: src=files/pg_hba.conf dest=$db_dir/pg_hba.conf
          owner=$db_user group=$db_user mode=0600
  notify:
    - restart postgres

- name: start postgres
  action: service name=postgresql state=running

- name: create role
  postgresql_user: fail_on_user=no login_user=$db_user name=root password=$db_passwd role_attr_flags=CREATEDB,CREATEROLE,SUPERUSER state=present

