- name: install libsemanage-python for ansible setsebool module
  yum: name=libsemanage-python state=present

- name: setsebool httpd_can_network_connect on
  seboolean: name=httpd_can_network_connect persistent=yes state=on

- name: copy iptables
  copy: src=files/iptables dest=/etc/sysconfig/iptables 
          owner=root group=root mode=0600 backup=yes

- name: ensure firewalld
  service: name=firewalld state=started enabled=yes

- name: copy rake tasks script
  template: src=templates/rake_tasks.sh.j2 dest=$ENV(HOME)/rake_tasks.sh owner=$ENV(USER) mode=0755

- name: db create
  #command: rake db:create:all chdir=$vmdb_dir
  shell: $ENV(HOME)/rake_tasks.sh

#- name: db migrate
#  command: bin/rake db:migrate chdir=$vmdb_dir
