- name: clone rbenv
  git: repo=git://github.com/sstephenson/rbenv.git dest=$ENV(HOME)/$rbenv_dir force=no

- name: clone ruby rbenv-gemset
  git: repo=git://github.com/jamis/rbenv-gemset.git dest=$ENV(HOME)/$rbenv_dir/plugins force=no

  # should not be necessary if rbenv path setup properly
- name: install rbenv-gemset to /usr/local/bin
  #command: cp /root/$rbenv_dir/plugins/libexec/$item /usr/local/bin/ creates=/usr/local/bin/$item
  file: src=$ENV(HOME)/$rbenv_dir/plugins/libexec/$item dest=/usr/local/bin/$item state=link
  with_items:
    - rbenv-gemset
    - rbenv-gemset-active
    - rbenv-gemset-create
    - rbenv-gemset-delete
    - rbenv-gemset-file
    - rbenv-gemset-list

- name: clone ruby-build
  git: repo=https://github.com/sstephenson/ruby-build.git dest=$ENV(HOME)/$rbenv_dir/plugins/ruby-build force=no

- name: add rbenv to path
  lineinfile: dest=$ENV(HOME)/$profile regexp="$rbenv_dir/bin" line="export PATH=$HOME/$rbenv_dir/bin:$PATH"

- name: add rbenv init to path
  lineinfile: dest=$ENV(HOME)/$profile regexp="rbenv init" line='eval "$(rbenv init -)"' insertafter=EOF

- name: source path
  shell: exec $ENV(SHELL) -l

# workaround since path not resolving
- name: install ruby-build standalone
  shell: ./install.sh chdir=$ENV(HOME)/$rbenv_dir/plugins/ruby-build creates=/usr/local/bin/ruby-build

- name: install ruby
  #command: rbenv install $ruby_ver creates=/usr/local/rbenv/versions/$ruby_ver/bin/ruby
  command: rbenv install $ruby_ver creates=$ENV(HOME)/.rbenv/versions/$ruby_ver/bin/ruby

- name: rbenv rehash
  command: rbenv rehash

- name: rbenv local
  command: rbenv local $ruby_ver chdir=$vmdb_dir

- name: create gemset cfme
  command: rbenv gemset create $ruby_ver cfme 

- name: install gemset cfme
  command: touch .rbenv-gemsets chdir=$vmdb_dir creates=$vmdb_dir/.rbenv-gemsets

- name: activate gemset
  command: rbenv gemset active chdir=$vmdb_dir

- name: rbenv rehash-b
  command: rbenv rehash chdir=$vmdb_dir

- name: gem install bundler
  gem: name=bundler state=present version=$bundler_ver

- name: rbenv rehash-c
  command: rbenv rehash chdir=$vmdb_dir

- name: bundle install
  command: bundle install --without metric_fu:sqlserver:qpid chdir=$vmdb_dir

