- name: clone rbenv
  git: repo=git://github.com/sstephenson/rbenv.git dest=$item/$rbenv_dir force=no
  with_env: HOME

- name: clone ruby rbenv-gemset
  git: repo=git://github.com/jamis/rbenv-gemset.git dest=$item/$rbenv_dir/plugins force=no
  with_env: HOME

  # FIXME: /root hard-coded for this manual install
  # should not be necessary if rbenv path setup properly
- name: install rbenv-gemset to /usr/local/bin
  #command: cp /root/$rbenv_dir/plugins/libexec/$item /usr/local/bin/ creates=/usr/local/bin/$item
  file: src=/root/$rbenv_dir/plugins/libexec/$item dest=/usr/local/bin/$item state=link
  with_items:
    - rbenv-gemset
    - rbenv-gemset-active
    - rbenv-gemset-create
    - rbenv-gemset-delete
    - rbenv-gemset-file
    - rbenv-gemset-list

- name: clone ruby-build
  git: repo=https://github.com/sstephenson/ruby-build.git dest=$item/$rbenv_dir/plugins/ruby-build force=no
  with_env: HOME

- name: add rbenv to path
  lineinfile: dest=$item/$profile regexp="$rbenv_dir/bin" line="export PATH=$HOME/$rbenv_dir/bin:$PATH"
  with_env: HOME

- name: add rbenv init to path
  lineinfile: dest=$item/$profile regexp="rbenv init" line='eval "$(rbenv init -)"' insertafter=EOF
  with_env: HOME

- name: source path
  shell: exec $SHELL -l

# workaround since path not resolving
- name: install ruby-build standalone
  shell: ./install.sh chdir=$item/$rbenv_dir/plugins/ruby-build creates=/usr/local/bin/ruby-build
  with_env: HOME

- name: install ruby
  #command: rbenv install $ruby_ver creates=/usr/local/rbenv/versions/$ruby_ver/bin/ruby
  command: rbenv install $ruby_ver creates=$item/.rbenv/versions/$ruby_ver/bin/ruby
  with_env: HOME

- name: rbenv rehash
  command: rbenv rehash

- name: rbenv local
  command: rbenv local $ruby_ver chdir=$vmdb_dir

- name: create gemset cfme
  command: rbenv gemset create $ruby_ver cfme 

- name: install gemset cfme
  command: touch .rbenv-gemsets chdir=$vmdb_dir creates=$vmdb_dir/.rbenv-gemsets

- name: activate gemset
  command: rbenv gemset active chdir=$vmdb_dir

- name: rbenv rehash-b
  command: rbenv rehash chdir=$vmdb_dir

- name: gem install bundler
  gem: name=bundler state=present version=$bundler_ver

- name: rbenv rehash-c
  command: rbenv rehash chdir=$vmdb_dir

# qpid failure? /usr/local/share/gems/gems/qpid_messaging-0.20.2
- name: bundle install
  command: bundle install --without=development metric_fu test_ui test sqlserver chdir=$vmdb_dir

