- name: clone rbenv
  git: repo=git://github.com/sstephenson/rbenv.git dest=$ENV(HOME)/$rbenv_dir 

- name: clone ruby rbenv-gemset
  git: repo=git://github.com/jamis/rbenv-gemset.git dest=$ENV(HOME)/$rbenv_dir/plugins/rbenv-gemset 

- name: clone ruby-build
  git: repo=https://github.com/sstephenson/ruby-build.git dest=$ENV(HOME)/$rbenv_dir/plugins/ruby-build 

- name: copy rbenv install script
  template: src=templates/ruby_install.sh.j2 dest=$ENV(HOME)/ruby_install.sh owner=$ENV(USER) mode=0755

- name: copy gemset create script
  template: src=templates/gemset_create.sh.j2 dest=$ENV(HOME)/gemset_create.sh owner=$ENV(USER) mode=0755

- name: copy bundle install script
  template: src=templates/bundle_install.sh.j2 dest=$ENV(HOME)/bundle_install.sh owner=$ENV(USER) mode=0755

- name: copy cfme aliases
  template: src=templates/cfme_aliases.sh.j2 dest=/etc/profile.d/cfme_aliases.sh
              owner=root group=root mode=0755 

- name: update $ENV(HOME)/$profile
  lineinfile: dest=$ENV(HOME)/$profile regexp='' insertafter=EOF
                line="export PATH=$HOME/$rbenv_dir/bin:$PATH\neval \"$(rbenv init -)\""

# not useful/effective in this context?
- name: source path
  #shell: sudo -iu $ENV(USER) source $ENV(HOME)/$profile 
  #shell: bash -lc '$ENV(HOME)/$profile' 
  shell: . $ENV(HOME)/$profile 

- name: install ruby
  shell: $ENV(HOME)/ruby_install.sh creates=$ENV(HOME)/$rbenv_dir/versions/$ruby_ver/bin/ruby

- name: gemset create
  shell: $ENV(HOME)/gemset_create.sh

- name: replace net-ldap ruby gem source
  lineinfile: dest=$vmdb_dir/Gemfile regexp='^gem .net-ldap.' line='gem "net-ldap", "~> 0.2.2"'

- name: bundle install
  shell: $ENV(HOME)/bundle_install.sh

